name: Publish Linux AMD64 Package

on:
  release:
    types: [published]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git User
        run: |
          git config user.name "dhernandez"
          git config user.email "dhernandez@users.noreply.github.com"

      - name: Push linux-amd64 subtree to its own repo
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git remote add linux-amd64-repo https://dhernandez:$GITHUB_TOKEN@github.com/satur-io/duckdb-php-clib-linux-amd64.git
          git subtree push --prefix=lib/linux-amd64 linux-amd64-repo main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Tag the package repo
        run: |
          git tag -f -a $GITHUB_REF_NAME -m "Release $GITHUB_REF_NAME"
          git push --tags https://dhernandez:$GITHUB_TOKEN@github.com/satur-io/duckdb-php-clib-linux-amd64.git --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
